import Link from "next/link";
import { CheckCircle2, ArrowRight, Kanban, ShieldCheck, ListChecks, ArrowUpRight } from "lucide-react";
import ThemeToggle from "../components/ThemeToggle";
import WorkspaceDemo from "../components/WorkspaceDemo";
export default function HomePage(){
 return <div className="min-h-[100dvh] bg-[var(--background)] text-slate-900">
 <header className="sticky top-0 z-30 border-b border-slate-200 bg-[var(--card)]"><div className="mx-auto flex h-[72px] max-w-7xl items-center justify-between gap-3 px-5 sm:px-8"><Link href="/" className="flex items-center gap-2.5 text-xl font-semibold tracking-tight"><span className="flex size-9 items-center justify-center rounded-xl bg-teal-700 text-white"><CheckCircle2 size={20}/></span>TaskFlow</Link><nav aria-label="Main navigation" className="hidden items-center gap-7 text-sm text-slate-600 md:flex"><a href="#workspace" className="hover:text-teal-700">Workspace</a><a href="#features" className="hover:text-teal-700">Features</a></nav><div className="flex items-center gap-3"><ThemeToggle/><Link href="/login" className="text-sm font-medium text-slate-600 hover:text-teal-700">Sign in</Link><Link href="/register" className="hidden items-center gap-2 rounded-lg bg-teal-700 px-4 py-2.5 text-sm font-medium text-white hover:bg-teal-800 sm:inline-flex">Get started<ArrowUpRight size={15}/></Link></div></div></header>
 <main>
 <section className="mx-auto grid max-w-7xl gap-8 px-5 pt-16 pb-14 sm:px-8 lg:grid-cols-[1.5fr_1fr] lg:gap-16 lg:pt-20 lg:pb-20">
 <div><p className="mb-6 flex items-center gap-2 text-xs font-medium text-teal-700"><span className="size-1.5 rounded-full bg-teal-600"/>A clearer way to work</p><h1 className="text-5xl font-medium leading-[1.08] tracking-[-.045em] sm:text-6xl lg:text-[68px]">Less scattered.<br/><span className="text-teal-700">More accomplished.</span></h1><p className="mt-6 max-w-md text-base leading-relaxed text-slate-500">Bring your tasks, priorities, and progress into one calm workspace. Make your next step a little clearer.</p><div className="mt-8 flex flex-wrap items-center gap-4"><Link href="/register" className="inline-flex items-center gap-3 rounded-lg bg-teal-700 px-6 py-3 text-sm font-medium text-white transition-colors hover:bg-teal-800">Get started<ArrowRight size={16}/></Link><a href="#workspace" className="inline-flex items-center gap-2 px-2 py-3 text-sm font-medium text-slate-700 hover:text-teal-700">Explore the workspace<ArrowRight size={16}/></a></div></div>
 <div className="flex flex-col justify-end border-l border-slate-200 pl-7 max-lg:mt-3 lg:pb-2"><span className="mb-5 flex size-12 items-center justify-center rounded-2xl border border-teal-200 bg-teal-50 text-teal-700"><ListChecks size={24}/></span><h2 className="max-w-xs text-2xl font-medium leading-snug tracking-tight">Good work starts with<br className="hidden lg:block"/> a clear head.</h2><p className="mt-4 max-w-xs text-sm leading-relaxed text-slate-500">Capture what matters. See what is moving. Finish the day knowing what you accomplished.</p><a href="#workspace" className="mt-6 inline-flex items-center gap-2 text-xs font-medium text-teal-700">Try the interactive board<ArrowUpRight size={14}/></a></div>
 </section>
 <section id="workspace" className="mx-auto max-w-7xl px-5 pb-20 sm:px-8"><WorkspaceDemo/></section>
 <section id="features" className="border-t border-slate-200 bg-[var(--card)]"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-16 sm:px-8 lg:grid-cols-[1fr_1.3fr]"><div><h2 className="max-w-sm text-3xl font-medium leading-tight tracking-tight">A place for everything.<br/><span className="text-slate-500">Space to focus.</span></h2><p className="mt-4 max-w-xs text-sm leading-relaxed text-slate-500">Just the tools you need to move work forward, without adding more to your day.</p></div><div className="divide-y divide-slate-200">{[{icon:Kanban,title:"Your work, your view",text:"Switch between a Kanban board and a focused list. Move tasks forward with a click."},{icon:ListChecks,title:"Progress you can see",text:"Keep track of what is waiting, what is in motion, and what is finished."},{icon:ShieldCheck,title:"A workspace you can manage",text:"Personal task spaces for members. A dedicated overview for administrators."}].map(({icon:Icon,title,text})=><div key={title} className="flex gap-5 py-6 first:pt-0 last:pb-0"><Icon size={21} className="mt-1 shrink-0 text-teal-700"/><div><h3 className="text-base font-medium">{title}</h3><p className="mt-2 max-w-md text-sm leading-relaxed text-slate-500">{text}</p></div></div>)}</div></div></section>
 </main>
 <footer className="border-t border-slate-200"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-4 px-5 py-6 text-xs text-slate-500 sm:flex-row sm:px-8"><span>© 2026 TaskFlow. Professional task and workflow software.</span><div className="flex items-center gap-5"><Link href="/login" className="hover:text-teal-700">Sign in</Link><Link href="/register" className="hover:text-teal-700">Get started</Link></div></div></footer>
 </div>;
}
